### ISSUE TITLE
Um conselho...

### ISSUE THREAD

**Issue by MellonFive** [suzanadossantos/site-capitao_america#1]
Os elementos "Títulos" e "Quadrinhos" podem estar melhor com um text-align: center e um font-size: 40px.
No footer, coloque sua redes sociais como github, instagram, facebook... Tenta dar uma olhada nesse site que fiz: https://do-you-want-coffee.vercel.app/

Qualquer dúvida entre em contato comigo. Bons códigos! :D

**Comment by suzanadossantos** [comment]
Olá! 

Obrigada pelas dicas! :)
